simpleblog/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'


urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

simpleblog/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.articles_list, name='list'),
    path('create/', views.article_create, name='create'),
    path('<slug:slug>/', views.article_detail, name='detail')
]

simpleblog/simpleblog/urls.py
from django.conf.urls import include
from django.conf.urls.static import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from articles import views as articles_views


urlpatterns = [
    path('', articles_views.articles_list, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

simpleblog/accounts/models.py
from django.db import models

# Create your models here.

simpleblog/articles/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

simpleblog/index/models.py
from django.db import models
from django.utils import timezone


class Comment(models.Model):
    name = models.CharField(max_length=20)
    comment = models.TextField()
    date_added = models.DateTimeField(default=timezone.now())

simpleblog/articles/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

simpleblog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log the user in
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log in the use
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm(data=request.POST)
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

simpleblog/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms


# Create your views here.
def articles_list(request):
    articles = Article.objects.all().order_by('date')

    return render(
        request, 'articles/articles_list.html', {'articles': articles}
    )


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)

    return render(
        request, 'articles/article_detail.html', {'article': article}
    )


@login_required(login_url='/accounts/login/')
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

simpleblog/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action={% url 'accounts:login' %} method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden", name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

simpleblog/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="/accounts/signup" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

simpleblog/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article"></div>
    <h2>CREATE NEW ARTICLE</h2>
    <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

simpleblog/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}"/>
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

simpleblog/articles/templates/articles/articles_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Articles List</h1>
    <br><br>
    <div class="articles">
        {% for article in articles %}
           <div class="articles">
               <h2> <a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a> </h2>
               <p>{{ article.snippet }}</p>
               <p>{{ article.date }}</p>
           </div>
        {% endfor %}
    </div>
{% endblock %}

simpleblog/templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title>
    </head>
    <body>
        <h1>About Us</h1>
        <p>We like django.</p>
    </body>
</html>

simpleblog/templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Simple Blog</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
<div class="wrapper">
    <h1><a href="{% url 'articles:list' %}"><img src="{% static 'logo.png' %}"/> </a></h1>
    <nav>
        <ul>
            {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
                <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
            {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
            {% endif %}
        </ul>
    </nav>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

simpleblog/templates/homepage.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Homepage</title>
    </head>
    <body>
        <h1>This is the homepage</h1>
        <p>Welcome to Simple Blog</p>
    </body>
</html>